spring:
  application:
    name: user-aggregator

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Data sources configuration
data-sources:
  sources:
    - name: data-base-1
      strategy: postgres
      url: jdbc:postgresql://localhost:5432/postgres
      user: user_postgre
      password: pass
      table: users_pg
      mapping:
        id: user_id
        username: login
        name: first_name
        surname: last_name
    - name: data-base-2
      strategy: mysql
      url: jdbc:mysql://localhost:3306/mysql_db?useSSL=false&allowPublicKeyRetrieval=true
      user: user_mysql
      password: pass
      table: users_mysql
      mapping:
        id: id
        username: username
        name: name
        surname: surname
